# Generated by Django 5.2.15 on 2026-07-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    """Canonical copy of the migration previously generated by InvenTree."""

    dependencies = [
        ("inventree_multi_site_importer", "0004_imageprefetch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captureimport",
            name="id",
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="imageprefetch",
            name="id",
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="mappingprofile",
            name="id",
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
